### PR TITLE
My new welcome message #PD-4

### PR DESCRIPTION
**Pull request by dcanadillas**
Let's merge new welcome message

### CODE REVIEW

**Comment by dcanadillas-kubecd** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **dcanadillas**

If they are not already assigned, you can assign the PR to them by writing `/assign @dcanadillas` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dcanadillas-kube%2Fdavid-godemo).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/dcanadillas-kube/david-godemo/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by dcanadillas-kubecd** [comment]
@dcanadillas: [cat image](https://thecatapi.com/?image_id=4pp)

<details>

In response to [this](https://github.com/dcanadillas-kube/david-godemo/pull/1#issuecomment-462908958):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by dcanadillas-kubecd** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dcanadillas-kube/david-godemo/pull/1#issuecomment-462909122" title="Approved">dcanadillas</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dcanadillas-kube%2Fdavid-godemo).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dcanadillas-kube/david-godemo/blob/master/OWNERS)~~ [dcanadillas]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by dcanadillas** [comment]
:star: PR built and available in a preview environment **dcanadillas-kube-david-godemo-pr-1** [here](http://david-godemo.jx-dcanadillas-kube-david-godemo-pr-1.35.187.39.22.nip.io)

**Pull request merged**
